// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: preference/v1/preference.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePreferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Preference *UpdatePreferenceRequest_Preference `protobuf:"bytes,2,opt,name=preference,proto3" json:"preference,omitempty"`
}

func (x *UpdatePreferenceRequest) Reset() {
	*x = UpdatePreferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preference_v1_preference_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceRequest) ProtoMessage() {}

func (x *UpdatePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preference_v1_preference_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_preference_v1_preference_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePreferenceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePreferenceRequest) GetPreference() *UpdatePreferenceRequest_Preference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type UpdatePreferenceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePreferenceReply) Reset() {
	*x = UpdatePreferenceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preference_v1_preference_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePreferenceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceReply) ProtoMessage() {}

func (x *UpdatePreferenceReply) ProtoReflect() protoreflect.Message {
	mi := &file_preference_v1_preference_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceReply.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceReply) Descriptor() ([]byte, []int) {
	return file_preference_v1_preference_proto_rawDescGZIP(), []int{1}
}

type GetPreferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPreferenceRequest) Reset() {
	*x = GetPreferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preference_v1_preference_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferenceRequest) ProtoMessage() {}

func (x *GetPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preference_v1_preference_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferenceRequest.ProtoReflect.Descriptor instead.
func (*GetPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_preference_v1_preference_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreferenceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPreferenceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Preference *GetPreferenceReply_Preference `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"`
}

func (x *GetPreferenceReply) Reset() {
	*x = GetPreferenceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preference_v1_preference_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreferenceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferenceReply) ProtoMessage() {}

func (x *GetPreferenceReply) ProtoReflect() protoreflect.Message {
	mi := &file_preference_v1_preference_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferenceReply.ProtoReflect.Descriptor instead.
func (*GetPreferenceReply) Descriptor() ([]byte, []int) {
	return file_preference_v1_preference_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreferenceReply) GetPreference() *GetPreferenceReply_Preference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type UpdatePreferenceRequest_Preference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip       bool `protobuf:"varint,1,opt,name=tip,proto3" json:"tip,omitempty"`
	Hotkeys   bool `protobuf:"varint,2,opt,name=hotkeys,proto3" json:"hotkeys,omitempty"`
	Guides    bool `protobuf:"varint,3,opt,name=guides,proto3" json:"guides,omitempty"`
	HideName  bool `protobuf:"varint,4,opt,name=hide_name,json=hideName,proto3" json:"hide_name,omitempty"`
	HideColor bool `protobuf:"varint,5,opt,name=hide_color,json=hideColor,proto3" json:"hide_color,omitempty"`
}

func (x *UpdatePreferenceRequest_Preference) Reset() {
	*x = UpdatePreferenceRequest_Preference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preference_v1_preference_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePreferenceRequest_Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceRequest_Preference) ProtoMessage() {}

func (x *UpdatePreferenceRequest_Preference) ProtoReflect() protoreflect.Message {
	mi := &file_preference_v1_preference_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceRequest_Preference.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceRequest_Preference) Descriptor() ([]byte, []int) {
	return file_preference_v1_preference_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdatePreferenceRequest_Preference) GetTip() bool {
	if x != nil {
		return x.Tip
	}
	return false
}

func (x *UpdatePreferenceRequest_Preference) GetHotkeys() bool {
	if x != nil {
		return x.Hotkeys
	}
	return false
}

func (x *UpdatePreferenceRequest_Preference) GetGuides() bool {
	if x != nil {
		return x.Guides
	}
	return false
}

func (x *UpdatePreferenceRequest_Preference) GetHideName() bool {
	if x != nil {
		return x.HideName
	}
	return false
}

func (x *UpdatePreferenceRequest_Preference) GetHideColor() bool {
	if x != nil {
		return x.HideColor
	}
	return false
}

type GetPreferenceReply_Preference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip       bool `protobuf:"varint,1,opt,name=tip,proto3" json:"tip,omitempty"`
	Hotkeys   bool `protobuf:"varint,2,opt,name=hotkeys,proto3" json:"hotkeys,omitempty"`
	Guides    bool `protobuf:"varint,3,opt,name=guides,proto3" json:"guides,omitempty"`
	HideName  bool `protobuf:"varint,4,opt,name=hide_name,json=hideName,proto3" json:"hide_name,omitempty"`
	HideColor bool `protobuf:"varint,5,opt,name=hide_color,json=hideColor,proto3" json:"hide_color,omitempty"`
}

func (x *GetPreferenceReply_Preference) Reset() {
	*x = GetPreferenceReply_Preference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preference_v1_preference_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreferenceReply_Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferenceReply_Preference) ProtoMessage() {}

func (x *GetPreferenceReply_Preference) ProtoReflect() protoreflect.Message {
	mi := &file_preference_v1_preference_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferenceReply_Preference.ProtoReflect.Descriptor instead.
func (*GetPreferenceReply_Preference) Descriptor() ([]byte, []int) {
	return file_preference_v1_preference_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetPreferenceReply_Preference) GetTip() bool {
	if x != nil {
		return x.Tip
	}
	return false
}

func (x *GetPreferenceReply_Preference) GetHotkeys() bool {
	if x != nil {
		return x.Hotkeys
	}
	return false
}

func (x *GetPreferenceReply_Preference) GetGuides() bool {
	if x != nil {
		return x.Guides
	}
	return false
}

func (x *GetPreferenceReply_Preference) GetHideName() bool {
	if x != nil {
		return x.HideName
	}
	return false
}

func (x *GetPreferenceReply_Preference) GetHideColor() bool {
	if x != nil {
		return x.HideColor
	}
	return false
}

var File_preference_v1_preference_proto protoreflect.FileDescriptor

var file_preference_v1_preference_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c,
	0x02, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x52, 0x0a, 0x0a, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x8c,
	0x01, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x69, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x68, 0x6f, 0x74, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x75, 0x69,
	0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x69, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x69, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x69, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x68, 0x69, 0x64, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x17, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf2,
	0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x50, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x1a, 0x8c, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x74, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x6b, 0x65, 0x79, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x75, 0x69, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x67, 0x75, 0x69, 0x64, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x69, 0x64, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x69, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x69, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x69, 0x64, 0x65, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x32, 0x95, 0x02, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x88, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x22,
	0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x7c, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b,
	0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x1b, 0x5a, 0x19, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_preference_v1_preference_proto_rawDescOnce sync.Once
	file_preference_v1_preference_proto_rawDescData = file_preference_v1_preference_proto_rawDesc
)

func file_preference_v1_preference_proto_rawDescGZIP() []byte {
	file_preference_v1_preference_proto_rawDescOnce.Do(func() {
		file_preference_v1_preference_proto_rawDescData = protoimpl.X.CompressGZIP(file_preference_v1_preference_proto_rawDescData)
	})
	return file_preference_v1_preference_proto_rawDescData
}

var file_preference_v1_preference_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_preference_v1_preference_proto_goTypes = []interface{}{
	(*UpdatePreferenceRequest)(nil),            // 0: api.preference.UpdatePreferenceRequest
	(*UpdatePreferenceReply)(nil),              // 1: api.preference.UpdatePreferenceReply
	(*GetPreferenceRequest)(nil),               // 2: api.preference.GetPreferenceRequest
	(*GetPreferenceReply)(nil),                 // 3: api.preference.GetPreferenceReply
	(*UpdatePreferenceRequest_Preference)(nil), // 4: api.preference.UpdatePreferenceRequest.Preference
	(*GetPreferenceReply_Preference)(nil),      // 5: api.preference.GetPreferenceReply.Preference
}
var file_preference_v1_preference_proto_depIdxs = []int32{
	4, // 0: api.preference.UpdatePreferenceRequest.preference:type_name -> api.preference.UpdatePreferenceRequest.Preference
	5, // 1: api.preference.GetPreferenceReply.preference:type_name -> api.preference.GetPreferenceReply.Preference
	0, // 2: api.preference.Preference.UpdatePreference:input_type -> api.preference.UpdatePreferenceRequest
	2, // 3: api.preference.Preference.GetPreference:input_type -> api.preference.GetPreferenceRequest
	1, // 4: api.preference.Preference.UpdatePreference:output_type -> api.preference.UpdatePreferenceReply
	3, // 5: api.preference.Preference.GetPreference:output_type -> api.preference.GetPreferenceReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_preference_v1_preference_proto_init() }
func file_preference_v1_preference_proto_init() {
	if File_preference_v1_preference_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_preference_v1_preference_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePreferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preference_v1_preference_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePreferenceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preference_v1_preference_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preference_v1_preference_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreferenceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preference_v1_preference_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePreferenceRequest_Preference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preference_v1_preference_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreferenceReply_Preference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_preference_v1_preference_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preference_v1_preference_proto_goTypes,
		DependencyIndexes: file_preference_v1_preference_proto_depIdxs,
		MessageInfos:      file_preference_v1_preference_proto_msgTypes,
	}.Build()
	File_preference_v1_preference_proto = out.File
	file_preference_v1_preference_proto_rawDesc = nil
	file_preference_v1_preference_proto_goTypes = nil
	file_preference_v1_preference_proto_depIdxs = nil
}
